repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.10
        args: [--line-length=88] # Set the desired line length for Black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.278
    hooks:
      - id: ruff

  - repo: local
    hooks:
      - id: export-requirements
        name: Export requirements from Poetry
        entry: bash -c 'cd "$(git rev-parse --show-toplevel)" && poetry export --without-hashes --format=requirements.txt > requirements.txt'
        language: system
